### ISSUE TITLE
Good job! 

### ISSUE THREAD

**Issue by yuchenlin** [RaleighHan/NumGuess#1]
Your program is completely correct and very easy to read. I think there are 2 main features of it.

1st Great command of syntaxes. The developer used just one do-while loops to generate 3 different random numbers. However, I have some suggestions about it. The difference between your code from others' is the method to generate the 3 different random numbers. This program is intended to generate all 3 numbers at once and to check if there are some numbers are double appeared.  It's correct but it may cause more time. The possibility that your loop just run once is (10x9x8)/(10^3), which is very high. Although, in this case the while loop will also check once if all numbers are different from each other. In another word, you program has 98% possibility to run as fast as others.

2nd The two lines of core code is easy to understand. In spite of the fact that they are pretty long, it's okay for beginning learners to use this kind of syntax. I believe when you have more experience of programming your code will be shorter. 

All in all, I think this program is pretty good. I'm looking forward to your next programs and your progress. ^ ^~

**Comment by RaleighHan** [comment]
Thank you for your encouragement!
