### ISSUE TITLE
Comments on NumGuess

### ISSUE THREAD

**Issue by Peter-Suchang** [RaleighHan/NumGuess#4]
Well done!
I think your program is quite well-organized. The variable names are meaningful. Several notes are added. And there are some blank lines dividing the program into several parts. All these make your program look clear, and make it easier to understand.
A detail is that I think the value of A and B don't need initialization every time after three numbers are entered. But this is so small a problem that it can be ignored. Another suggestion is that some more detailed notes, for example, some explanation of the meaning of A and B, should be added.
Generally speaking, this program is quite good.

**Comment by RaleighHan** [comment]
Thank you!
